version: '3.8'
services:
  # Ngninx Proxy Manager for routing, exposing, https certificates, access controll.
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  # Guess The Song Frontend
  client:
    image: 'thaemisch/gts-client:${ENV_ARCH}'
    restart: unless-stopped
    ports:
      - '5001:3000'
    environment:
      - CLIENT_ID=${ENV_CLIENT_ID}
      - REDIRECT_URI=${ENV_REDIRECT_URI}
      - SERVER_URL=${ENV_SERVER_URL}
  # Guess The Song Backend
  server:
    image: 'thaemisch/gts-server:${ENV_ARCH}'
    restart: unless-stopped
    ports:
      - '5002:3000'
      - '5003:8080'
    environment:
      - CLIENT_ID=${ENV_CLIENT_ID}
      - CLIENT_SECRET=${ENV_CLIENT_SECRET}
      - REDIRECT_URI=${ENV_REDIRECT_URI}
    volumes:
      - ./database:/app/server/db
