version: '3.8'
services:
  # Ngninx Proxy Manager for routing, exposing, https certificates, access controll.
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  # Guess The Song Frontend
  frontend:
    image: 'thaemisch/gts-client:latest'
    restart: unless-stopped
    ports:
      - '5001:80'
    environment:
      - CLIENT_ID=YOURSPOTIFYCLIENTIDHERE
      - REDIRECT_URI=https://YOURFRONTENDURL/auth
      - SERVER_URL=YOURSERVERURL
  # Guess The Song Backend
  #backend:
  #  image: 'thaemisch/gts-server:latest'
  #  restart: unless-stopped
  #  ports:
  #    - '5002:3000'
  #    - '5003:8080'
  #  volumes:
  #    - ./env:/env
